### ISSUE TITLE
Params missing in some yaml

### ISSUE THREAD

**Issue by sgiardie** [ACTCollaboration/ACT-DR6-parameters#11]
Hi @HTJense, there are some parameters missing in some yaml files:

- an `alpha_tSZ` block in [`params/foregrounds.yaml`](https://github.com/ACTCollaboration/ACT-DR6-parameters/blob/main/params/foregrounds.yaml), which is in the current default so we need it
- defining `calG_all` in [act_dr6.yaml](https://github.com/ACTCollaboration/ACT-DR6-parameters/blob/main/likelihoods/act_dr6.yaml) and [act_dr6_polcuts.yaml](https://github.com/ACTCollaboration/ACT-DR6-parameters/blob/main/likelihoods/act_dr6_polcuts.yaml)

(I would open a PR to solve these but you should grant me the permission to push branches)

Maybe in general it can be useful to add the default yaml files to use for ACT+Planck and other data combination. This is useful for people that will run the different parameter extensions and that need to find default files here.

**Comment by HTJense** [comment]
Resolved #12.
